### ISSUE TITLE
has no attribute 'squeezenet1_1'

### ISSUE THREAD

**Issue by dovanchan** [lizeng614/SqueezeNet-Neural-Style-Pytorch#2]
DOVANtekiMacBook-Pro:squeezeNet-Neural-Style-Pytorch-master DOVAN$ python neural_style.py --style /Users/DOVAN/deeprely/squeezeNet-Neural-Style-Pytorch-master/img_data/style/qqq.jpg --content /Users/DOVAN/deeprely/squeezeNet-Neural-Style-Pytorch-master/img_data/img/dovan.jpg
Traceback (most recent call last):
  File "neural_style.py", line 153, in <module>
    model = models.squeezenet1_1(pretrained=True)
AttributeError: 'module' object has no attribute 'squeezenet1_1'

no module?I have installed the pytorch

**Comment by CoderInPajamas** [comment]
Hi,
I think you got the error because you didn't install pytorch and torchvision from source, squeezeNet is not in the latest release of torchvision so you need to install torchvision from source to use it, although i do think a new release is coming soon.
To install from source you can fellow this:
https://github.com/pytorch/pytorch#from-source
and https://github.com/pytorch/vision#installation

**Comment by dovanchan** [comment]
Hi,
Now I have done what you said,I installed the pytorch from source  like here:

running install_egg_info
running egg_info
creating torch.egg-info
writing requirements to torch.egg-info/requires.txt
writing torch.egg-info/PKG-INFO
writing top-level names to torch.egg-info/top_level.txt
writing dependency_links to torch.egg-info/dependency_links.txt
writing manifest file 'torch.egg-info/SOURCES.txt'
reading manifest file 'torch.egg-info/SOURCES.txt'
writing manifest file 'torch.egg-info/SOURCES.txt'
Copying torch.egg-info to /Users/DOVAN/anaconda2/lib/python2.7/site-packages/torch-0.1.10+e4b4e51-py2.7.egg-info
running install_scripts


But when I run ：
DOVANtekiMacBook-Pro:squeezeNet-Neural-Style-Pytorch-master DOVAN$ python neural_style.py --style /Users/DOVAN/deeprely/squeezeNet-Neural-Style-Pytorch-master/img_data/style/qqq.jpg --content /Users/DOVAN/deeprely/squeezeNet-Neural-Style-Pytorch-master/img_data/img/dovan.jpg

it still give me the error ：
Traceback (most recent call last):
  File "neural_style.py", line 153, in <module>
    model = models.squeezenet1_1(pretrained=True)
AttributeError: 'module' object has no attribute 'squeezenet1_1'

My python version is 2.7;
Thanks

**Comment by CoderInPajamas** [comment]
Hi,
sorry i didn't make it clear in my readme file. you will also need install your torchvision from source. I had everything installed in an anaconda python3.6 environment, and the code is also written in python 3.

**Comment by dovanchan** [comment]
Hi,@lizeng614
Can you give me your contact email or Wechat,I am a student from Guangzhou university ,grade 3
These months I am researching neural style and I am really interested.
I hope I can often communicate with you~

**Comment by dovanchan** [comment]
Hi,Can you update your readme.md ,let us know how to use this code,I still can not install the enviroment successful.I hope you can update it~

**Comment by CoderInPajamas** [comment]
Hi, I am writing my thesis so currently I am not maintaining this repo. But I would guess Pytorch already have a release that contains squeezeNet, but then you probably will have to update the some part of the code, (and I really encourage you to do so). Otherwise I would see If I can find a weekend to update my code or maybe after I finish my thesis.
